from src.models.persona_model import Persona
from src.models.proyecto_model import Proyecto
from src.models.unidad_ejecutora_model import UnidadEjecutora
from src.models.direccion_territorial_model import DireccionTerritorial
from src.models.tipo_proyecto_model import TipoProyecto
from src.models.ruta_model import Ruta
from src.models.tramo_sector import TramoSector
from src.models.funcionalidad_carretera_model import FuncionalidadCarretera
from src.models.clasificacion_proyecto_model import ClasificacionProyecto
from src.models.modo_transporte_model import ModoTransporte
from src.models.categorizacion_carretera_model import CategorizacionCarretera
from src.models.contrato_model import Contrato
from src.models.departamento_model import Departamento
from src.models.municipio_model import Municipio